services:
  obolonka:
    build:
      context: ./obolonka
    ports:
      - "5173:3000"
    networks:
      - mererza


  backend_troian:
    image: vitaliktroian04/smart-energy-stability:latest
    ports:
      - "6028:8085"
    restart: always

  pokazovaSlurzba:
    image: bondarenkorodion/slurzba1
    ports:
      - "3000:3000"
    networks:
      - mererza

networks:
  mererza:
    driver: bridge
